<a href="https://colab.research.google.com/github/Armin-HassanzadehHassanabad/Machine-Learning/blob/main/Encoding%2C_scaling%2C_and_duplicate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import io
from google.colab import files

In [ ]:
uploaded = files.upload()
df = pd.read_csv(io.BytesIO(uploaded[list(uploaded.keys())[0]]))

NameError: name 'files' is not defined

**Label Encoding**

In [ ]:
df['sex'][df['sex'] == 1] = 'M'
df['sex'][df['sex'] == 0] = 'F'
df.head()

/tmp/ipython-input-2274118759.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['sex'][df['sex'] == 1] = 'M'
/tmp/ipython-input-2274118759.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sex'][df['sex'] == 1] = 'M'
/tmp/ipython-input-2274118759.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'M' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df['sex'][df['sex'] == 1] = 'M'

,Age (age in year),sex,chest pain,blood pressure,cholestoral,blood sugar,electrocardiographic,heart rate,exercise induced,depression,slope,ca,thal,c
0,63,M,1,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,37,M,3,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
2,41,F,2,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0
3,56,M,2,120.0,236.0,0.0,0.0,178.0,0.0,0.8,1.0,0.0,3.0,0
4,57,F,4,120.0,354.0,0.0,0.0,163.0,1.0,0.6,1.0,0.0,3.0,0

In [ ]:
from sklearn.preprocessing import LabelEncoder


LE = LabelEncoder()
LE.fit(df['sex'])
df['sex'] = LE.transform(df['sex'])
df.head()

,Age (age in year),sex,chest pain,blood pressure,cholestoral,blood sugar,electrocardiographic,heart rate,exercise induced,depression,slope,ca,thal,c
0,63,1,1,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,37,1,3,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
2,41,0,2,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0
3,56,1,2,120.0,236.0,0.0,0.0,178.0,0.0,0.8,1.0,0.0,3.0,0
4,57,0,4,120.0,354.0,0.0,0.0,163.0,1.0,0.6,1.0,0.0,3.0,0

In [ ]:
df.loc[3, 'sex'] = np.nan
df_dummy = pd.get_dummies(df, dummy_na=True, drop_first=True)
df_dummy.head()

,Age (age in year),sex,chest pain,blood pressure,cholestoral,blood sugar,electrocardiographic,heart rate,exercise induced,depression,slope,ca,thal,c
0,63,1.0,1,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,37,1.0,3,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
2,41,0.0,2,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0
3,56,NaN,2,120.0,236.0,0.0,0.0,178.0,0.0,0.8,1.0,0.0,3.0,0
4,57,0.0,4,120.0,354.0,0.0,0.0,163.0,1.0,0.6,1.0,0.0,3.0,0

In [ ]:
from sklearn.preprocessing import MinMaxScaler

rsc = MinMaxScaler()
df_scaled = pd.DataFrame(rsc.fit_transform(df), columns=df.columns, index=df.index)
df_scaled.head()

,Age (age in year),sex,chest pain,blood pressure,cholestoral,blood sugar,electrocardiographic,heart rate,exercise induced,depression,slope,ca,thal,c
0,0.714286,1.0,0.000000,0.490741,0.285714,1.0,1.0,0.603053,0.0,0.370968,1.0,0.0,0.75,0.0
1,0.183673,1.0,0.666667,0.351852,0.318533,0.0,0.0,0.885496,0.0,0.564516,1.0,0.0,0.00,0.0
2,0.265306,0.0,0.333333,0.351852,0.229730,0.0,1.0,0.770992,0.0,0.225806,0.0,0.0,0.00,0.0
3,0.571429,NaN,0.333333,0.259259,0.291506,0.0,0.0,0.816794,0.0,0.129032,0.0,0.0,0.00,0.0
4,0.591837,0.0,1.000000,0.259259,0.519305,0.0,0.0,0.702290,1.0,0.096774,0.0,0.0,0.00,0.0

**Detecting Noise or Imbalance**

In [ ]:
df.ca.value_counts()

ca
0.0    179
1.0     65
2.0     38
3.0     20
9.0      1
Name: count, dtype: int64

In [ ]:
df.ca.value_counts(dropna=False)

ca
NaN    294
0.0    179
1.0     65
2.0     38
3.0     20
9.0      1
Name: count, dtype: int64

In [ ]:
df["ca"][df["ca"] == 9] = 0

/tmp/ipython-input-574900428.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["ca"][df["ca"] == 9] = 0
/tmp/ipython-input-574900428.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ca"][df["ca"] == 9] = 0

In [ ]:
df.ca.value_counts()

ca
0.0    180
1.0     65
2.0     38
3.0     20
Name: count, dtype: int64

**Handling Duplicate Data**

In [ ]:
dfdup = df[df.duplicated()]
dfdup

,Age (age in year),sex,chest pain,blood pressure,cholestoral,blood sugar,electrocardiographic,heart rate,exercise induced,depression,slope,ca,thal,c
265,49,0.0,2,110.0,NaN,0.0,0.0,160.0,0.0,0.0,NaN,NaN,NaN,0

In [ ]:
df_dub = df.drop_duplicates()
print(df.shape, df_dub.shape)

(597, 14) (596, 14)

In [ ]:
df[df.duplicated(keep='last')]

,Age (age in year),sex,chest pain,blood pressure,cholestoral,blood sugar,electrocardiographic,heart rate,exercise induced,depression,slope,ca,thal,c
221,49,0.0,2,110.0,NaN,0.0,0.0,160.0,0.0,0.0,NaN,NaN,NaN,0